name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v3

      - name: Subir archivos estáticos
        uses: actions/upload-pages-artifact@v2
        with:
          path: .

      - name: Desplegar a GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2 